- app/src/test-load-invite/index-load-invite.html
- app/src/test-load-invite/requireConfig-load-invite.js
- app/src/test-load-invite/src/app.js
Simple example showing how to load an invite's property payload using the GlympseLoader module exposed from the adapter
FYI @kevinATglympse
> Load invite example

- app/src/adapter/models/Account.js
- app/src/lib/utils.js
Using localStorage if it is available, store all settings for account in 'accountInfo' property in __gacfg
> ENG-11517: Using localStorage

- README.md
- app/src/GlympseAdapterDefines.js
- app/src/adapter/CardsController.js
- app/src/adapter/Client.js
- app/src/adapter/CoreController.js
- app/src/adapter/models/Account.js
Added `cards.joinRequest(requestConfig)` endpoint
> ENG-11483: Added cards.joinRequest API endpoint

- README.md
- app/src/GlympseAdapterDefines.js
- app/src/adapter/CardsController.js
- app/src/adapter/Client.js
Added `cards.joinRequestCancel($request_id)` API endpoint
> ENG-11493: Cancel request to join card

- README.md
- app/src/GlympseAdapterDefines.js
- app/src/adapter/CardsController.js
- app/src/adapter/Client.js
Added `cards.getActiveJoinRequests()` API endpoint
> ENG-11673: Get list of active join card requests

- README.md
- app/src/GlympseAdapterDefines.js
- app/src/adapter/CardsController.js
- app/src/adapter/Client.js
- app/src/adapter/CoreController.js
- app/src/adapter/GlympseLoader.js
- app/src/adapter/models/Account.js
- Renamed `AccountInit` event to `AccountLoginStatus` (breaking change),
- Added `core.generateAuthToken()` API
> ENG-11497: generateAuthToken

- app/src/adapter/models/Card.js
Member ticket is updating now when we start sharing
> Member data is updated now

- app/src/adapter/models/Account.js
Small fix: adapter log into account automatically after creation only for anonymous mode
> Autologin is sent after account creation only for anonymous mode

- app/src/adapter/models/Account.js
> unify AccountCreateStatus event data structure with other places

- app/src/adapter/Client.js
- app/src/adapter/models/MemberTicket.js
- pass correct card id for info data stream updates
- pass normalized invite code in data stream
- add "created_time" getter to member_ticket model 
necessary for [ENG-11791](http://jira.glympse.com/browse/ENG-11791)
> Data stream changes (for ENG-11791)

- app/src/adapter/CardsController.js
- app/src/adapter/models/Account.js
Now it handles expired/invalid token during init process. Probably need to think about better approach during implementing centralization of all ajax call in http://jira.glympse.com/browse/ENG-11657.
> ENG-11902: [Adapter] Expired auth token is not updated

- app/src/adapter/CardsController.js
- app/src/adapter/Client.js
- app/src/adapter/CoreController.js
- app/src/adapter/GlympseLoader.js
- app/src/adapter/models/Account.js
- app/src/adapter/models/GlympseInvite.js
- app/src/lib/ajax.js
**IN-PROGRESS**
done:
- `ajax` helper created
- Account/GlympseInvite re-factored to use new utility
- added FixMe about token handling (marked as [oauth_token])
todo:
- Cards Ctrl refactoring (use new ajax utils)
- central token expiration handling
@Glympse/web Not ready yet, but can be reviewed to probably note some problems. 
Require PR from app to work correctly: https://github.com/Glympse/web-app-viewer/pull/106.
> ENG-11657: [Adapter] Centralization of the ajax calls

- app/src/adapter/models/Account.js
> ENG-11874: Externalize API keys to use with core service

- app/src/adapter/models/Card.js
http://jira.glympse.com/browse/ENG-12009
Fixes for case 2
Case 1: https://github.com/Glympse/web-app-viewer/pull/139
> ENG-12009: Fixed start/stop sharing logic

- app/src/GlympseAdapterDefines.js
- app/src/adapter/ViewerMonitor.js
> ENG-12145: Partner's app metadata

- app/src/adapter/models/Card.js
For https://github.com/Glympse/web-app-viewer/pull/169.
> add userId to member_removed event

- app/src/adapter/Client.js
> If same user shares same inviteCode to diff cards -> send invites related events for all cards.

- .eslintrc
- app/src/adapter/CardsController.js
- app/src/adapter/models/Account.js
- app/src/adapter/models/Card.js
Disable eslint consistent-return-value rule, fix a ton of small formatting issues.
> Eslint fixes

- app/src/adapter/CardsController.js
- app/src/adapter/models/Card.js
Passing a timestamp with card activity events
> Added timestamp to card activity events

- app/src/GlympseAdapterDefines.js
- app/src/adapter/Client.js
http://jira.glympse.com/browse/ENG-12547
> ENG-12547: Added manual sending end_time and completed events

- app/src/lib/utils.js
> Sync with viewer’s storage implementation

- app/src/GlympseAdapter.js
- app/src/GlympseAdapterDefines.js
http://jira.glympse.com/browse/FE-375
> FE-375:Alias global namespace references in glympse-adapter as necessary

- app/index-build.html
- app/index.html
- app/src/adapter/Client.js
- app/src/test-client/index-client.html
- app/src/test-host/index-host.html
- app/src/test-load-invite/index-load-invite.html
> Align to hard-coded https protocol

- app/src/GlympseAdapter.js
- app/src/GlympseAdapterDefines.js
- app/src/adapter/models/Account.js
- app/src/lib/md5.js
- app/src/lib/utils.js
- grunt/bowerRequirejs.js
> FE-335 Use a hash of the apiKey as the named-index for glympse-adapter's credentials caching

- app/src/adapter/Client.js
> [bugfix] pass-through invite status events in not-cards mode

- app/src/adapter/ViewerMonitor.js
- Deleted stored properties if an invite has been removed
- Updated to using RAF timer
- Align timer on specific invite instead of global
@Glympse/web - PTAL
> Fix for messaging if an invite has been removed

- app/src/lib/ajax.js
> FE-924: properly handle empty auth token for auth requests

- README.md
- app/src/GlympseAdapterDefines.js
- app/src/adapter/Client.js
- app/src/adapter/ViewerMonitor.js
> propagate ZOOM_CHANGED event from the viewer

- app/src/adapter/models/PublicGroup.js
- take the latest event for the particular member
- ignore invite if it already assigned to the member
@Glympse/web, @j5kay, PTAL.
**NOTE:** the shuttle  built with this version of adapter was deployed to prod/dev together with another fix https://github.com/Glympse/enroute-journey/pull/249
> FE-1004: [IHG] Multiple trucks displaying in journey

- CHANGELOG.md
- README.md
- app/src/adapter/CoreController.js
> FE-1115 Glympse Adapter: update `getEtaInfo` api to support waypoints

- app/src/adapter/ViewerMonitor.js
Original issue: https://jira.glympse.com/browse/FE-1320.
> do not process outdated events form invite's data-stream

- README.md
- app/src/adapter/Host.js
- app/src/common/oasis/iframe_adapter.js
https://www.pivotaltracker.com/story/show/157596563
> #157596563: allow to disable sandbox on iframe (host mode)

- app/src/GlympseAdapterDefines.js
- app/src/adapter/ViewerMonitor.js
https://www.pivotaltracker.com/story/show/157818608
added 'eta_range' property
> #157818608 - Refactor TruGreen journey to utilize `quasi_range` property on invite

- app/src/GlympseAdapterDefines.js
- app/src/adapter/ViewerMonitor.js
> removed previously added era_range property

- app/src/GlympseAdapterDefines.js
- app/src/adapter/Client.js
- app/src/adapter/CoreController.js
https://www.pivotaltracker.com/story/show/157818608
> #157818608 - adding interface to get eta_range object

- .gitignore
- app/src/GlympseAdapter.js
- app/src/adapter/models/Account.js
- app/src/common/oasis/message_channel.js
- grunt/aliases.js
- grunt/jsdoc.js
- package.json
@Glympse/web , PTAL!
added jsdoc grunt plugin
https://www.pivotaltracker.com/story/show/158872195
Added no JSDocs because I don't know what params mean.
> #158872195 Provide grunt task to generate JSDocs for the rest projects

- app/src/lib/image.js
PT: https://www.pivotaltracker.com/story/show/162770541
> Append a mock parameter to XHR request
